name: Lint Code Base

on:
  pull_request:
    branches:
      - master
      - main
      - develop

jobs:
  build:
    name: Lint Code Base
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Lint Code Base
        uses: super-linter/super-linter@v8.2.1
        env:
          VALIDATE_ALL_CODEBASE: false
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          ACTIONS_RUNNER_DEBUG: true
          VALIDATE_SQLFLUFF: true
          SQLFLUFF_CONFIG_FILE: ".sqlfluff"
